### ISSUE TITLE
Color interpretation bug in Safari 9

### ISSUE THREAD

**Issue by balthatrix** [STRd6/pixel-editor#55]
![screenshot 2015-11-25 10 33 18](https://cloud.githubusercontent.com/assets/5818492/11406099/ab780c18-9360-11e5-9471-5942bae949bf.png)

**Comment by balthatrix** [comment]
It also manifests here in Safari 9:
http://pixieengine.com/pixel-editor

**Comment by STRd6** [comment]
Thanks for the report!

What operating system are you running?

**Comment by balthatrix** [comment]
No problem!  One of my users actually found the bug.  

We are both using Mac/intel.

Se

**Comment by balthatrix** [comment]
Any word on this bug?  For some reason I thought I checked and saw it was fixed here http://pixieengine.com/pixel-editor, but apparently it wasn't.

Anyhow, no rush, I'm just curious.

**Comment by STRd6** [comment]
I haven't got a chance to look into it yet. That other issue was to get a simpler UI for the color picker and a larger active color swatch.

**Comment by balthatrix** [comment]
Ahh okay.  Thanks for keeping me in the loop!

Se
